steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Copying dist/ to GCS bucket..."
        gsutil -m cp -r dist/* gs://agilityui.bementalagile.com/

timeout: '600s'
