steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing Node.js..."
        apt-get update && apt-get install -y curl && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Installing dependencies..."
        npm ci
        echo "Building project..."
        npm run build
        echo "Copying dist/ to GCS bucket..."
        gsutil -m cp -r dist/* gs://agilityui.bementalagile.com/

timeout: '600s'
